### ISSUE TITLE
jdk-15 not currently available as "select" button on trends graph

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-dashboard-v2#14]

**Comment by smlambert** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/pull/7#issuecomment-642139066

**Comment by andrew-m-leonard** [comment]
jdk-15 now showing, now that Hotspot build is released. Trends graph loads the versions dynamically, was added by AdamT: https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/pull/11
