### ISSUE TITLE
Dashboard for the deprecated V2 API not working

### ISSUE THREAD

**Issue by nickebbitt** [AdoptOpenJDK/openjdk-dashboard-v2#15]
Whilst working on https://github.com/AdoptOpenJDK/openjdk-api-v3/pull/306 I spotted that the [old V2 dashboard](https://dash.adoptopenjdk.net/) is still running but appears to be broken.

One option is to look at fixing it but maybe a better option would be to redirect to the [latest dashboard](https://dash-v2.adoptopenjdk.net/) based on the V3 API.

<img width="1912" alt="Screen Shot 2020-11-12 at 9 56 18 PM" src="https://user-images.githubusercontent.com/5111725/99444953-cd934e80-2914-11eb-8ca8-93b6e11e2cb6.png">

**Comment by smlambert** [comment]
Redirect is a good option.

**Comment by smlambert** [comment]
Believe this is now resolved.
