### ISSUE TITLE
Feature Request: Normalized graphs for comparing trends

### ISSUE THREAD

**Issue by Scott-Young-6746** [AdoptOpenJDK/openjdk-dashboard-v2#16]
When comparing the trends in OpenJ9 vs Hotspot the differences in absolute values squashes the trends in OpenJ9 into a (more or less) flat line. It would be helpful to see a normalized line graph (probably to the maximum point on each line) to show the trends side by side in a more comparable way.

**Comment by karianna** [comment]
We're no longer enhancing the legacy AdoptOpenJDK dashboard.  Please see the dashboard at Eclipse Adoptium.
