### ISSUE TITLE
Dashboard website is currently down

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-dashboard-v2#19]
The website dash.adoptopenjdk.net is currently not responding.

It appears that the Dependabot has made [a breaking change](https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/commit/8a206a40414f73a877cf2fa522d16ab0763c6d6d) to the CNAME file on the `gh-pages` branch, changing it from `dash.adoptopenjdk.net` to `dash-v2.adoptopenjdk.net`.

Note that the master branch still has `dash-v2.adoptopenjdk.net`.

**Comment by tellison** [comment]
Also updated the [repo settings](https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/settings) GitHub Pages configuration to change the Custom domain from `dash-v2.adoptopenjdk.net` to `dash.adoptopenjdk.net`

**Comment by tellison** [comment]
Cross referencing [sxa's comment on the PR](https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/pull/20#pullrequestreview-609547509):

> we should identify why that commit went in and whether it's likely to get redone via automation before considering this resolved

**Comment by karianna** [comment]
The website is up so closing this and will raise new issues on the GH deploy failing
