### ISSUE TITLE
Display download stats using reactjs libraries

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-dashboard-v2#2]
With the completion of https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/44, we can use the API to pull the historical download count and compare operating systems, sources, versions and dates. A feature should be added that will allow users to view historical download trends across various fields. This should be possible using reactjs libraries (https://react-dashboard.cube.dev/, https://react-bootstrap.github.io/, etc) 

Deliverables
-------------
- [x] Await conversion of website to react.js
- [ ] Show download stats over a specified amount of time
- [ ] Graph download trends across jdk versions, architectures and sources
- [x] Ensure the stability of the vanilla js website is not upset by the inclusion of react elements

**Comment by gdams** [comment]
@llxia has done some awesome work to setup this new React version of the dashboard! I've moved this issue to the new home so we can continue to track it's progress.

**Comment by M-Davies** [comment]
@adam-thorpe Are you currently working on this? If so, I can close this issue as a dup?

**Comment by karianna** [comment]
We're no longer enhancing the legacy AdoptOpenJDK dashboard.  Please see the dashboard at Eclipse Adoptium.
