### ISSUE TITLE
https://dash.adoptopenjdk.net/trends is not available

### ISSUE THREAD

**Issue by CarmenDelgadoEclipse** [AdoptOpenJDK/openjdk-dashboard-v2#41]
When requesting to view the trends from the AdoptOpenJDK dashboard, we cannot do it, and the message is "Something went wrong."

**Comment by smlambert** [comment]
I do not have that problem, but I do notice that I can not go directly to this URL https://dash.adoptium.net/trends
I have to first go to https://dash.adoptium.net and then click on Trends link on the left side of the dashboard.

**Comment by CarmenDelgadoEclipse** [comment]
Neither can't see the data from the main URL.

**Comment by smlambert** [comment]
I see, its the old dashboard that is experiencing a problem.


```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'length')
    at c.max (Trends.js:227:18)
    at c.render (Trends.js:240:97)
    at Za (react-dom.production.min.js:182:1)
    at Ga (react-dom.production.min.js:181:1)
    at Ro (react-dom.production.min.js:263:1)
    at Lu (react-dom.production.min.js:246:1)
    at Ru (react-dom.production.min.js:246:1)
    at Cu (react-dom.production.min.js:239:1)
    at react-dom.production.min.js:123:1
    at exports.unstable_runWithPriority (scheduler.production.min.js:19:1)
```

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/blob/master/src/Graph/Trends.js#L240 - need to see why the categories or categories2 is undefined.

https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/blob/master/src/Graph/Trends.js#L48-L64 - is where they get defined.  Can check whether calls to API are returning things... https://api.adoptopenjdk.net/v3/info/available_releases 

Depending on when this problem started happening, perhaps some of the dependabot bumps introduced problems, https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/pull/40 bumped `moment` to a different version for example.

**Comment by karianna** [comment]
I think the dashboard we use comes from github.com/dash.adoptium.net - this one needs to be deprecated / removed.

**Comment by smlambert** [comment]
I assumed that since we still continue to serve binaries out of the AdoptOpenJDK API also, that we would still want to keep track of the download numbers from it (and our cumulative download numbers would be the numbers from dash.adoptopenjdk.net + dash.adoptium.net).  Is that no longer the case?

**Comment by karianna** [comment]
We should discuss at the PMC for sure (always a little odd as the old AdoptOpenJDK org no longer really exists, but it's mostly the same folks).  @johnoliver will be able to give us the options there.

**Comment by johnoliver** [comment]
The trend failing to appear was due to a temporary glitch in the api that has been fixed, should return to normal
